version: '3.8'

services:
  # 1. 데이터베이스 서비스 (PostgreSQL)
  postgres-db:
    image: postgres:15-alpine
    container_name: wms-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: wms_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
     - ./db_data:/var/lib/postgresql/data

  # 2. 백엔드 서비스 (Spring Boot)
  backend:
    build:
      context: .
      dockerfile: wms-inventory/Dockerfile
    container_name: wms-backend
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/wms_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=DEBUG
      - LOGGING_LEVEL_ORG_HIBERNATE=ERROR
    depends_on:
      - postgres-db

  # 3. 프론트엔드 서비스 (React + Nginx)
  frontend:
    build:
      context: ./wms-frontend # 리액트폴더명
      dockerfile: Dockerfile
    container_name: wms-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: